In [2]:
from sklearn import datasets
iris = datasets.load_iris()
x = iris.data
y = iris.target


In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [4]:
y_test

array([1, 1, 1, 1, 0, 1, 2, 0, 1, 0, 2, 1, 2, 1, 1, 0, 0, 1, 0, 2, 1, 2,
       2, 1, 1, 0, 0, 2, 2, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1, 1, 2,
       1])

In [6]:
from sklearn import tree 
classifier = tree.DecisionTreeClassifier()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

In [9]:
assert type(y_pred) == type(y_test), 'in correct type'

In [11]:
help(recall_score)

Help on function recall_score in module sklearn.metrics._classification:

recall_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')
    Compute the recall.
    
    The recall is the ratio ``tp / (tp + fn)`` where ``tp`` is the number of
    true positives and ``fn`` the number of false negatives. The recall is
    intuitively the ability of the classifier to find all the positive samples.
    
    The best value is 1 and the worst value is 0.
    
    Read more in the :ref:`User Guide <precision_recall_f_measure_metrics>`.
    
    Parameters
    ----------
    y_true : 1d array-like, or label indicator array / sparse matrix
        Ground truth (correct) target values.
    
    y_pred : 1d array-like, or label indicator array / sparse matrix
        Estimated targets as returned by a classifier.
    
    labels : array-like, default=None
        The set of labels to include when ``average != 'binary'``, and their
        ord

In [13]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, confusion_matrix, accuracy_score 

print('accuracy', accuracy_score(y_test, y_pred))
print('recall', recall_score(y_test, y_pred, average='micro'))
print('precision', precision_score(y_test, y_pred, average='micro'))
print('\n confusion matrix \n', confusion_matrix(y_test, y_pred))

accuracy 0.9333333333333333
recall 0.9333333333333333
precision 0.9333333333333333

 confusion matrix 
 [[11  0  0]
 [ 0 17  2]
 [ 0  1 14]]
